name:       HAL
version:    0.1.0.0
github:     "EpitechPromo2024/B-FUN-501-MPL-5-1-HAL-jori.bashllari"
license:    BSD3
author:     "Jor Bashllari"
maintainer: "altnate2000@gmail.com"
copyright:  "me"

extra-source-files:
- README.md
- ChangeLog.md
- stdlib.scm

# Metadata used when publishing your package
synopsis: interpreter for a minimalist dialect of LISP
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/EpitechIT2020/B-FUN-501-TIR-5-1-HAL-besart.cerri#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline
- containers
- mtl
# - pretty-simple

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  HAL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - HAL

tests:
  HAL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HAL
    - hedgehog
    - hspec
